---
- hosts: pfservers
  name: Run example tests
  become: True

  vars:
    # put your test suites to try here
    test_suites:
      - pfcron

  tasks:
    - name: Run Venom testsuites
      command: '/usr/local/pf/t/venom/venom-wrapper.sh /usr/local/pf/t/venom/test_suites/{{ item }}'
      args:
        chdir: '/usr/local/pf/t/venom'
      loop: '{{ test_suites }}'
      vars:
        venom_wrapper_args:
          # temp, overcome two Venom issues:
          # - tap: https://github.com/ovh/venom/issues/428
          # - when running test suite one by one, previous logs and results are overriden
          # Venom will create one directory per test suite to store results
          VENOM_COMMON_FLAGS: '--format=tap --output-dir=/usr/local/pf/t/venom/results/{{ item }}'

      # add inventory__group_environment to Ansible environment
      # useful to make env vars available for Venom
      environment: '{{ inventory__group_environment | d({})
                       | combine(venom_wrapper_args | d({})) }}'


