/components/schemas/config/DomainsList:
  allOf:
  - $ref: '#/components/schemas/Iterable'
  - properties:
      items:
        items:
          $ref: '#/components/schemas/config/Domain'
        type: array
    type: object
