/components/schemas/config/FirewallsList:
  allOf:
  - $ref: '#/components/schemas/Iterable'
  - properties:
      items:
        items:
          $ref: '#/components/schemas/config/Firewall'
        type: array
    type: object
