/components/schemas/config/MaintenanceTasksList:
  allOf:
  - $ref: '#/components/schemas/Iterable'
  - properties:
      items:
        items:
          $ref: '#/components/schemas/config/MaintenanceTask'
        type: array
    type: object
