/components/schemas/config/Realm:
  properties:
    admin_strip_username:
      description: Should the usernames matching this realm be stripped when used
        on the administration interface
      type: string
    domain:
      description: The domain to use for the authentication in that realm
      type: string
    id:
      description: Realm
      type: string
    options:
      description: You can add FreeRADIUS options in the realm definition
      type: string
    portal_strip_username:
      description: Should the usernames matching this realm be stripped when used
        on the captive portal
      type: string
    radius_strip_username:
      description: Should the usernames matching this realm be stripped when used
        in the authorization phase of 802.1x. Note that this doesn't control the stripping
        in FreeRADIUS, use the options above for that.
      type: string
  required:
  - id
  type: object
