/components/schemas/config/RealmsList:
  allOf:
  - $ref: '#/components/schemas/Iterable'
  - properties:
      items:
        items:
          $ref: '#/components/schemas/config/Realm'
        type: array
    type: object
