/components/schemas/config/SourcesList:
  allOf:
  - $ref: '#/components/schemas/Iterable'
  - properties:
      items:
        items:
          $ref: '#/components/schemas/config/Source'
        type: array
    type: object
