/components/schemas/config/SwitchesList:
  allOf:
  - $ref: '#/components/schemas/Iterable'
  - properties:
      items:
        items:
          $ref: '#/components/schemas/config/Switch'
        type: array
    type: object
