---
################################################################################
# COMMON PARAMETERS
################################################################################
before_script:
  - unset http_proxy ; unset https_proxy
  - env | grep ^CI_

################################################################################
# STAGES
################################################################################
stages:
  - build_images
  - build_pkg
  - build_maintenance
  - sign
  - publish
  - test
  - upload
  - post_upload

################################################################################
# VARIABLES
################################################################################
variables:
  PFBUILD_CENTOS_7_IMG: inverseinc/pfbuild-centos-7
  PFBUILD_DEB_STRETCH_IMG: inverseinc/pfbuild-debian-stretch
  CIDIR: ci
  CILIBDIR: ci/lib
  PACKERDIR: $CIDIR/packer
  MAINTDIR: $CILIBDIR/maintenance
  INSTDIR: $CILIBDIR/test
  UPLOAD_DIR: $CILIBDIR/upload
  RPM_DIR: rpm
  DEB_DIR: debian
  VAGRANT_DIR: addons/vagrant
  PUBLIC_REPO_URL: http://packetfence.org/downloads/PacketFence
  # env variables
  ANSIBLE_FORCE_COLOR: "true"
  ANSIBLE_STDOUT_CALLBACK: yaml
  VAGRANT_FORCE_COLOR: "true"


################################################################################
# TEMPLATES
################################################################################

########################################
# TRIGGERS
########################################
# triggers for dev jobs (devel and other development branches)
.job_dev_triggers:
  # run jobs on "devel" branch (push, schedules and web)
  # run jobs on any branches/tags via "Run pipeline", except:
  # - vX.Y.Z tag
  # - maintenance/X.Y branches
  # - feature/packer-.* branches
  only:
    - /^devel$/
    - web
  except:
    - /^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$/
    - /^maintenance/[[:digit:]]+\.[[:digit:]]+$/
    - /^feature/packer-.*$/

# triggers for release jobs
.job_release_triggers:
  # run job on release tag (vX.Y.Z) (push and web)
  # no schedule on tag
  # exclude branches to avoid trigger when a branch is called vX.Y.X
  only:
    - /^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$/
  except:
    - branches

# common triggers for jobs use for release and dev
.job_dev_and_release_triggers:
  # run jobs on "devel" branch *or* vX.Y.Z tag (push, schedules and web)
  # run jobs on any branches/tags via "Run pipeline", except:
  # - maintenance/X.Y branches
  # - feature/packer-.* branches
  only:
    - /^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$/
    - /^devel$/
    - web
  except:
    - /^maintenance/[[:digit:]]+\.[[:digit:]]+$/
    - /^feature/packer-.*$/

# triggers for maintenance jobs
.job_maintenance_triggers:
  # run job on maintenance branches (push, schedules and web)
  # allow on all maintenance branches with a .gitlab-ci.yml (starting from 8.0)
  only:
    - /^maintenance/[[:digit:]]+\.[[:digit:]]+$/

########################################    
# JOBS
########################################
.pfbuild_job:
  stage: build_images
  tags:
    - shell

.build_job:
  stage: build_pkg
  artifacts:
    expire_in: 1 day
    paths:
      - result/*
  tags:
    - docker

.maintenance_build_job:
  stage: build_maintenance
  artifacts:
    expire_in: 1 day
    paths:
      - result/*
  tags:
    - docker

.maintenance_sign_job:
  stage: sign
  artifacts:
    expire_in: 1 day
    paths:
      - result/*
  dependencies:
    - build_maintenance_centos_7
    - build_maintenance_debian_stretch
  tags:
    - shell

.test_job:
  stage: test
  dependencies:
    - pages
  tags:
    - inverse.ca
    - shell

.maintenance_deploy_job:
  stage: upload
  dependencies:
    - sign_maintenance
  variables:
    DEPLOY_USER: reposync
    DEPLOY_HOST: web.inverse.ca
    MAINT_DEPLOY_DIR: ${CI_ENVIRONMENT_NAME}
  script:
    - ./${UPLOAD_DIR}/deploy-artifacts.sh maintenance
  tags:
    - shell
    
.deploy_deb_job:
  stage: upload
  dependencies:
    - sign_dev_and_release
  variables:
    DEPLOY_USER: root
    DEB_DEPLOY_DIR: ${CI_ENVIRONMENT_NAME}
    DEPLOY_UPDATE: "/builds/bin/ci-repo-deploy deb ${CI_ENVIRONMENT_NAME}"
  script:
    - ./${UPLOAD_DIR}/deploy-artifacts.sh deb
  # run job on runners tag with inverse AND shell
  tags:
    - inverse
    - shell

.deploy_rpm_job:
  stage: upload
  dependencies:
    - sign_dev_and_release
  variables:
    DEPLOY_USER: root
    RPM_DEPLOY_DIR: ${CI_ENVIRONMENT_NAME}
    DEPLOY_SRPMS: "no"
    DEPLOY_UPDATE: "/builds/bin/ci-repo-deploy rpm ${CI_ENVIRONMENT_NAME}"
  script:
    - ./${UPLOAD_DIR}/deploy-artifacts.sh rpm
  # run job on runners tag with inverse AND shell
  tags:
    - inverse
    - shell

.post_upload_rpm_packetfence-release_job:
  stage: post_upload
  dependencies:
    - sign_dev_and_release
  variables:
    DEPLOY_USER: reposync
    DEPLOY_HOST: web.inverse.ca
  environment:
    name: ${PKG_DEST_NAME}
    url: ${PUBLIC_REPO_URL}/RHEL7
  script:
    - ./${UPLOAD_DIR}/deploy-artifacts.sh packetfence-release
  tags:
    - shell

.rpm_script:
  script:
    # temp
    - echo "%git_commit $CI_COMMIT_SHA" >> ${RPM_DIR}/.rpmmacros
    - cp ${RPM_DIR}/.rpmmacros ${HOME}
    - ci-build-pkg ${RPM_DIR}

.deb_script:
  script:
    - ./${CIDIR}/debian/convert-to-native-package.sh
    - cp ${CIDIR}/debian/.devscripts ${HOME}
    # temp
    - make conf/git_commit_id
    - quilt push
    - ci-build-pkg ${DEB_DIR}
  variables:
    QUILT_PATCHES: ${DEB_DIR}/patches

.maintenance_build_script:
  script:
    - ./${MAINTDIR}/build_and_sign_maintenance_artifacts.sh build

.maintenance_sign_script:
  script:
    - ./${MAINTDIR}/build_and_sign_maintenance_artifacts.sh sign

.test_script:
  script:
    - make -C ${INSTDIR} test
  after_script:
    - make -C ${INSTDIR} teardown
    

################################################################################
# STAGES
################################################################################

########################################
# BUILD_IMAGES JOBS
########################################
pfbuild_manual:
  extends: .pfbuild_job
  script:
    - make -e -C ${PACKERDIR} pfbuild
  # job need to be explicitly started
  # will not block other stages/jobs
  # will not run when we click "Run pipeline"
  when: manual

pfbuild_test:
  extends: .pfbuild_job
  script:
    # remove 'feature/' prefix from branch name
    - export DOCKER_TAG=${CI_COMMIT_REF_NAME#feature/}
    - make -e -C ${PACKERDIR} pfbuild
  only:
    - /^feature/packer-.*$/

# build a docker image at release
# used to build release packages, maintenance artifacts for maintenance
pfbuild_release:
  extends:
    - .pfbuild_job
    - .job_release_triggers
  variables:
    ANSIBLE_CENTOS_GROUP: stable_centos
    ANSIBLE_DEBIAN_GROUP: stable_debian
    ANSIBLE_RUBYGEMS_GROUP: stable_rubygems
    # set to empty value to remove '-except' arg
    PACKER_EXTRA_ARG: ' '
    DOCKER_TAG: ${CI_COMMIT_TAG}
  script:
    # extra tag to release images: maintenance-X-Y
    # permit to simplify definition of maintenance jobs below
    # based on their branch name using CI_COMMIT_REF_SLUG
    # CI_COMMIT_TAG contains vX.Y.Z
    # PF_RELEASE_REV contains X.Y
    # DOCKER_EXTRA_TAG contains maintenance-X-Y
    - PF_RELEASE_REV=$(perl -ne 'print $1 if (m/.*?(\d+\.\d+)./)' conf/pf-release)
    - export DOCKER_EXTRA_TAG=maintenance-${PF_RELEASE_REV/./-}
    - make -e -C ${PACKERDIR} pfbuild

########################################
#  BUILD_PKG JOBS
########################################
# build_pkg jobs for development
build_pkg_dev_centos_7:
  image: ${PFBUILD_CENTOS_7_IMG}:latest
  extends:
    - .build_job
    - .job_dev_triggers
    - .rpm_script

build_pkg_dev_debian_stretch:
  image: ${PFBUILD_DEB_STRETCH_IMG}:latest
  extends:
    - .build_job
    - .job_dev_triggers
    - .deb_script

# build_pkg jobs for release
# CI_COMMIT_TAG contains vX.Y.X
build_pkg_release_centos_7:
  image: ${PFBUILD_CENTOS_7_IMG}:${CI_COMMIT_TAG}
  extends:
    - .build_job
    - .job_release_triggers
    - .rpm_script

build_pkg_release_debian_stretch:
  image: ${PFBUILD_DEB_STRETCH_IMG}:${CI_COMMIT_TAG}
  extends:
    - .build_job
    - .job_release_triggers
    - .deb_script

########################################
# BUILD_MAINTENANCE JOBS
########################################
# CI_COMMIT_REF_SLUG contains maintenance-X-Y
build_maintenance_centos_7:
  image: ${PFBUILD_CENTOS_7_IMG}:${CI_COMMIT_REF_SLUG}
  extends:
    - .maintenance_build_job
    - .maintenance_build_script
    - .job_maintenance_triggers

build_maintenance_debian_stretch:
  image: ${PFBUILD_DEB_STRETCH_IMG}:${CI_COMMIT_REF_SLUG}
  extends:
    - .maintenance_build_job
    - .maintenance_build_script
    - .job_maintenance_triggers

########################################
# SIGN JOBS
########################################
sign_dev_and_release:
  # GPG_USER_ID see GitLab variable
  # only use when executor is docker
  image: buildpkg/debian:buster
  stage: sign
  script:
    - ci-sign-pkg
  dependencies:
    - build_pkg_dev_centos_7
    - build_pkg_dev_debian_stretch
    - build_pkg_release_centos_7
    - build_pkg_release_debian_stretch
  artifacts:
    expire_in: 1 day
    paths:
      - result/*
  # run job on runners tag with inverse.ca AND shell
  tags:
    - shell
  extends:
    - .job_dev_and_release_triggers

sign_maintenance:
  # GPG_USER_ID see GitLab variable
  extends:
    - .maintenance_sign_job
    - .maintenance_sign_script
    - .job_maintenance_triggers

########################################
# PUBLISH JOBS
########################################
pages:
  # only use when executor is docker
  image: buildpkg/debian:buster
  stage: publish
  variables:
    PAGES_DIR: public
    PAGES_HOST: gitlab.io
  environment:
    name: PPA
    url: http://${CI_PROJECT_NAMESPACE}.${PAGES_HOST}/${CI_PROJECT_NAME}
  script:
    - ci-pages-ppa
    - ci-pages-home
    - ci-pages-tree
  dependencies:
    - sign_dev_and_release
  artifacts:
    expire_in: 1 day
    paths:
      - public
  # run job on runners tag with inverse.ca AND shell
  tags:
    - shell
  extends:
    - .job_dev_and_release_triggers

########################################
# TEST JOBS
########################################
test_pkg_dev_and_release_centos_7:
  variables:
    VM_NAME: pfcen7dev
  extends:
    - .test_job
    - .test_script
    - .job_dev_and_release_triggers
  when: manual

test_pkg_dev_and_release_debian_stretch:
  variables:
    VM_NAME: pfdeb9dev
    PERL_UNIT_TESTS: no
  extends:
    - .test_job
    - .test_script
    - .job_dev_and_release_triggers
  when: manual
    
########################################
# UPLOAD JOBS
########################################
deploy_rpm_dev:
  extends:
    - .deploy_rpm_job
    - .job_dev_triggers
  environment:
    name: devel/x86_64
    url: ${PUBLIC_REPO_URL}/RHEL7/${CI_ENVIRONMENT_NAME}

deploy_deb_dev:
  extends:
    - .deploy_deb_job
    - .job_dev_triggers
  environment:
    name: debian-devel
    url: ${PUBLIC_REPO_URL}/${CI_ENVIRONMENT_NAME}

deploy_rpm_release:
  extends:
    - .deploy_rpm_job
    - .job_release_triggers
  environment:
    name: x86_64
    url: ${PUBLIC_REPO_URL}/RHEL7/${CI_ENVIRONMENT_NAME}

deploy_deb_release:
  extends:
    - .deploy_deb_job
    - .job_release_triggers
  environment:
    name: debian-lastrelease
    url: ${PUBLIC_REPO_URL}/${CI_ENVIRONMENT_NAME}

# we deploy artifacts for all distributions in one shot
deploy_maintenance:
  extends:
    - .maintenance_deploy_job
    - .job_maintenance_triggers
  environment:
    name: maintenance
    url: ${PUBLIC_REPO_URL}/${CI_ENVIRONMENT_NAME}

########################################
# POST_UPLOAD JOBS
########################################
# we deploy packetfence-release RPM with
# a fixed name *outside* a RPM repo
# for first installation
post_upload_rpm_packetfence-release_dev:
  extends:
    - .post_upload_rpm_packetfence-release_job
    - .job_dev_triggers
  variables:
    PKG_DEST_NAME: packetfence-release-7.devel.noarch.rpm

post_upload_rpm_packetfence-release_release:
  extends:
    - .post_upload_rpm_packetfence-release_job
    - .job_release_triggers
  variables:
    PKG_DEST_NAME: packetfence-release-7.stable.noarch.rpm
