- hosts: pfservers, service_venom, nodes
  name: Get Venom logs on all VM
  become: True
  tags: logs

  vars:
    # result_dir = full path to 'results' directory at root of PF sources tree
    result_dir: '{{ lookup("env", "RESULT_DIR") }}'

  tasks:
    - name: Sanitize logs
      shell: '{{ venom_dir }}/utils/sanitize-venom-logs.sh &> /dev/null'
      args:
        executable: '/bin/bash'
      no_log: True
      # to make Psono variables available
      environment: '{{ inventory__group_environment | d({}) }}'

    # Store archive into result_dir/hostname/src
    - name: Get logs on runner
      fetch:
        src: '{{ venom_dir }}/results.tar.gz'
        dest: '{{ result_dir }}'

