/config/billing_tier/{billing_tier_id}:
  delete:
    description: Remove an item
    operationId: api.v1.Config::BillingTiers.remove
    parameters: []
    responses:
      '204':
        description: Deleted a config item
  description: pf::UnifiedApi::Controller::Config::BillingTiers
  get:
    description: Get an item
    operationId: api.v1.Config::BillingTiers.get
    parameters: []
    responses:
      '200':
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfigBillingTier'
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
  patch:
    description: Update an item
    operationId: api.v1.Config::BillingTiers.update
    parameters: []
    requestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ConfigBillingTier'
    responses:
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
  put:
    description: Replace an item
    operationId: api.v1.Config::BillingTiers.replace
    parameters: []
    requestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ConfigBillingTier'
    responses:
      '201':
        $ref: '#/components/responses/Created'
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
