/config/syslog_parsers:
  description: pf::UnifiedApi::Controller::Config::SyslogParsers
  get:
    description: List items
    operationId: api.v1.Config::SyslogParsers.list
    parameters: []
    responses:
      '200':
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfigSyslogParsersList'
        description: List
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
