/config/traffic_shaping_policies:
  description: pf::UnifiedApi::Controller::Config::TrafficShapingPolicies
  get:
    description: List items
    operationId: api.v1.Config::TrafficShapingPolicies.list
    parameters: []
    responses:
      '200':
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfigTrafficShapingPoliciesList'
        description: List
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
