/config/violation/{violation_id}:
  delete:
    description: Remove an item
    operationId: api.v1.Config::Violations.remove
    parameters:
    - in: path
      name: violation_id
      schema:
        type: string
    responses:
      '204':
        description: Deleted a config item
  description: pf::UnifiedApi::Controller::Config::Violations
  get:
    description: Get an item
    operationId: api.v1.Config::Violations.get
    parameters:
    - in: path
      name: violation_id
      schema:
        type: string
    responses:
      '200':
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfigViolation'
        description: Item
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
  patch:
    description: Update an item
    operationId: api.v1.Config::Violations.update
    parameters:
    - in: path
      name: violation_id
      schema:
        type: string
    requestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ConfigViolation'
    responses:
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
  put:
    description: Replace an item
    operationId: api.v1.Config::Violations.replace
    parameters:
    - in: path
      name: violation_id
      schema:
        type: string
    requestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ConfigViolation'
    responses:
      '201':
        $ref: '#/components/responses/Created'
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
