ConfigFingerbankSettingsList:
  allOf:
  - $ref: '#/components/schemas/Iterable'
  - properties:
      items:
        description: List
        items:
          $ref: '#/components/schemas/ConfigFingerbankSetting'
        type: array
    type: object
  description: List
