ConfigMaintenanceTasksMeta:
  discriminator:
    propertyName: type
  oneOf:
  - properties:
      meta:
        properties:
          batch:
            $ref: '#/components/schemas/Meta'
          id:
            $ref: '#/components/schemas/Meta'
          schedule:
            $ref: '#/components/schemas/Meta'
          status:
            $ref: '#/components/schemas/Meta'
          timeout:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
          window:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          batch:
            $ref: '#/components/schemas/Meta'
          id:
            $ref: '#/components/schemas/Meta'
          schedule:
            $ref: '#/components/schemas/Meta'
          status:
            $ref: '#/components/schemas/Meta'
          timeout:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          id:
            $ref: '#/components/schemas/Meta'
          schedule:
            $ref: '#/components/schemas/Meta'
          status:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          batch:
            $ref: '#/components/schemas/Meta'
          history_batch:
            $ref: '#/components/schemas/Meta'
          history_timeout:
            $ref: '#/components/schemas/Meta'
          history_window:
            $ref: '#/components/schemas/Meta'
          id:
            $ref: '#/components/schemas/Meta'
          schedule:
            $ref: '#/components/schemas/Meta'
          session_batch:
            $ref: '#/components/schemas/Meta'
          session_timeout:
            $ref: '#/components/schemas/Meta'
          session_window:
            $ref: '#/components/schemas/Meta'
          status:
            $ref: '#/components/schemas/Meta'
          timeout:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
          window:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          batch:
            $ref: '#/components/schemas/Meta'
          id:
            $ref: '#/components/schemas/Meta'
          schedule:
            $ref: '#/components/schemas/Meta'
          status:
            $ref: '#/components/schemas/Meta'
          timeout:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
          window:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          batch:
            $ref: '#/components/schemas/Meta'
          id:
            $ref: '#/components/schemas/Meta'
          schedule:
            $ref: '#/components/schemas/Meta'
          status:
            $ref: '#/components/schemas/Meta'
          timeout:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          batch:
            $ref: '#/components/schemas/Meta'
          id:
            $ref: '#/components/schemas/Meta'
          rotate:
            $ref: '#/components/schemas/Meta'
          rotate_batch:
            $ref: '#/components/schemas/Meta'
          rotate_timeout:
            $ref: '#/components/schemas/Meta'
          rotate_window:
            $ref: '#/components/schemas/Meta'
          schedule:
            $ref: '#/components/schemas/Meta'
          status:
            $ref: '#/components/schemas/Meta'
          timeout:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
          window:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          id:
            $ref: '#/components/schemas/Meta'
          schedule:
            $ref: '#/components/schemas/Meta'
          status:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          id:
            $ref: '#/components/schemas/Meta'
          schedule:
            $ref: '#/components/schemas/Meta'
          status:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          id:
            $ref: '#/components/schemas/Meta'
          schedule:
            $ref: '#/components/schemas/Meta'
          status:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          batch:
            $ref: '#/components/schemas/Meta'
          id:
            $ref: '#/components/schemas/Meta'
          schedule:
            $ref: '#/components/schemas/Meta'
          status:
            $ref: '#/components/schemas/Meta'
          timeout:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          id:
            $ref: '#/components/schemas/Meta'
          schedule:
            $ref: '#/components/schemas/Meta'
          status:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          batch:
            $ref: '#/components/schemas/Meta'
          id:
            $ref: '#/components/schemas/Meta'
          rotate:
            $ref: '#/components/schemas/Meta'
          rotate_batch:
            $ref: '#/components/schemas/Meta'
          rotate_timeout:
            $ref: '#/components/schemas/Meta'
          rotate_window:
            $ref: '#/components/schemas/Meta'
          schedule:
            $ref: '#/components/schemas/Meta'
          status:
            $ref: '#/components/schemas/Meta'
          timeout:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
          window:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          delete_window:
            $ref: '#/components/schemas/Meta'
          id:
            $ref: '#/components/schemas/Meta'
          schedule:
            $ref: '#/components/schemas/Meta'
          status:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
          unreg_window:
            $ref: '#/components/schemas/Meta'
          voip:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          id:
            $ref: '#/components/schemas/Meta'
          schedule:
            $ref: '#/components/schemas/Meta'
          status:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
          window:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          id:
            $ref: '#/components/schemas/Meta'
          process_switchranges:
            $ref: '#/components/schemas/Meta'
          schedule:
            $ref: '#/components/schemas/Meta'
          status:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          id:
            $ref: '#/components/schemas/Meta'
          schedule:
            $ref: '#/components/schemas/Meta'
          status:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          id:
            $ref: '#/components/schemas/Meta'
          schedule:
            $ref: '#/components/schemas/Meta'
          status:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          batch:
            $ref: '#/components/schemas/Meta'
          id:
            $ref: '#/components/schemas/Meta'
          schedule:
            $ref: '#/components/schemas/Meta'
          status:
            $ref: '#/components/schemas/Meta'
          timeout:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          id:
            $ref: '#/components/schemas/Meta'
          schedule:
            $ref: '#/components/schemas/Meta'
          status:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          certificates:
            $ref: '#/components/schemas/Meta'
          delay:
            $ref: '#/components/schemas/Meta'
          id:
            $ref: '#/components/schemas/Meta'
          schedule:
            $ref: '#/components/schemas/Meta'
          status:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          batch:
            $ref: '#/components/schemas/Meta'
          id:
            $ref: '#/components/schemas/Meta'
          schedule:
            $ref: '#/components/schemas/Meta'
          status:
            $ref: '#/components/schemas/Meta'
          timeout:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
          window:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          batch:
            $ref: '#/components/schemas/Meta'
          id:
            $ref: '#/components/schemas/Meta'
          schedule:
            $ref: '#/components/schemas/Meta'
          status:
            $ref: '#/components/schemas/Meta'
          timeout:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
          window:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          batch:
            $ref: '#/components/schemas/Meta'
          id:
            $ref: '#/components/schemas/Meta'
          schedule:
            $ref: '#/components/schemas/Meta'
          status:
            $ref: '#/components/schemas/Meta'
          timeout:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
          window:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          batch:
            $ref: '#/components/schemas/Meta'
          id:
            $ref: '#/components/schemas/Meta'
          schedule:
            $ref: '#/components/schemas/Meta'
          status:
            $ref: '#/components/schemas/Meta'
          timeout:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
          window:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          id:
            $ref: '#/components/schemas/Meta'
          schedule:
            $ref: '#/components/schemas/Meta'
          status:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          id:
            $ref: '#/components/schemas/Meta'
          schedule:
            $ref: '#/components/schemas/Meta'
          status:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          batch:
            $ref: '#/components/schemas/Meta'
          id:
            $ref: '#/components/schemas/Meta'
          schedule:
            $ref: '#/components/schemas/Meta'
          status:
            $ref: '#/components/schemas/Meta'
          timeout:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
          window:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
