ConfigProvisioning:
  description: 'Choose one of the request bodies by discriminator (`type`). '
  discriminator:
    mapping:
      accept: '#/components/schemas/ConfigProvisioningSubTypeAccept'
      airwatch: '#/components/schemas/ConfigProvisioningSubTypeAirwatch'
      android: '#/components/schemas/ConfigProvisioningSubTypeAndroid'
      deny: '#/components/schemas/ConfigProvisioningSubTypeDeny'
      dpsk: '#/components/schemas/ConfigProvisioningSubTypeDpsk'
      google_workspace_chromebook: '#/components/schemas/ConfigProvisioningSubTypeGoogleWorkspaceChromebook'
      intune: '#/components/schemas/ConfigProvisioningSubTypeIntune'
      jamf: '#/components/schemas/ConfigProvisioningSubTypeJamf'
      kandji: '#/components/schemas/ConfigProvisioningSubTypeKandji'
      mobileconfig: '#/components/schemas/ConfigProvisioningSubTypeMobileconfig'
      mobileiron: '#/components/schemas/ConfigProvisioningSubTypeMobileiron'
      sentinelone: '#/components/schemas/ConfigProvisioningSubTypeSentinelone'
      windows: '#/components/schemas/ConfigProvisioningSubTypeWindows'
    propertyName: type
  oneOf:
  - $ref: '#/components/schemas/ConfigProvisioningSubTypeMobileconfig'
  - $ref: '#/components/schemas/ConfigProvisioningSubTypeAndroid'
  - $ref: '#/components/schemas/ConfigProvisioningSubTypeDpsk'
  - $ref: '#/components/schemas/ConfigProvisioningSubTypeSentinelone'
  - $ref: '#/components/schemas/ConfigProvisioningSubTypeIntune'
  - $ref: '#/components/schemas/ConfigProvisioningSubTypeDeny'
  - $ref: '#/components/schemas/ConfigProvisioningSubTypeAccept'
  - $ref: '#/components/schemas/ConfigProvisioningSubTypeGoogleWorkspaceChromebook'
  - $ref: '#/components/schemas/ConfigProvisioningSubTypeMobileiron'
  - $ref: '#/components/schemas/ConfigProvisioningSubTypeKandji'
  - $ref: '#/components/schemas/ConfigProvisioningSubTypeJamf'
  - $ref: '#/components/schemas/ConfigProvisioningSubTypeAirwatch'
  - $ref: '#/components/schemas/ConfigProvisioningSubTypeWindows'
