ConfigPkiProvidersMeta:
  discriminator:
    propertyName: type
  oneOf:
  - properties:
      meta:
        properties:
          ca_cert_path:
            $ref: '#/components/schemas/Meta'
          ca_cert_path_upload:
            $ref: '#/components/schemas/Meta'
          cn_attribute:
            $ref: '#/components/schemas/Meta'
          cn_format:
            $ref: '#/components/schemas/Meta'
          country:
            $ref: '#/components/schemas/Meta'
          id:
            $ref: '#/components/schemas/Meta'
          locality:
            $ref: '#/components/schemas/Meta'
          organization:
            $ref: '#/components/schemas/Meta'
          organizational_unit:
            $ref: '#/components/schemas/Meta'
          password:
            $ref: '#/components/schemas/Meta'
          server_cert_path:
            $ref: '#/components/schemas/Meta'
          server_cert_path_upload:
            $ref: '#/components/schemas/Meta'
          state:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
          url:
            $ref: '#/components/schemas/Meta'
          username:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          ca_cert_path:
            $ref: '#/components/schemas/Meta'
          ca_cert_path_upload:
            $ref: '#/components/schemas/Meta'
          cn_attribute:
            $ref: '#/components/schemas/Meta'
          cn_format:
            $ref: '#/components/schemas/Meta'
          country:
            $ref: '#/components/schemas/Meta'
          host:
            $ref: '#/components/schemas/Meta'
          id:
            $ref: '#/components/schemas/Meta'
          locality:
            $ref: '#/components/schemas/Meta'
          organization:
            $ref: '#/components/schemas/Meta'
          password:
            $ref: '#/components/schemas/Meta'
          port:
            $ref: '#/components/schemas/Meta'
          postalcode:
            $ref: '#/components/schemas/Meta'
          profile:
            $ref: '#/components/schemas/Meta'
          proto:
            $ref: '#/components/schemas/Meta'
          revoke_on_unregistration:
            $ref: '#/components/schemas/Meta'
          server_cert_path:
            $ref: '#/components/schemas/Meta'
          server_cert_path_upload:
            $ref: '#/components/schemas/Meta'
          state:
            $ref: '#/components/schemas/Meta'
          streetaddress:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
          username:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          ca_cert_path:
            $ref: '#/components/schemas/Meta'
          ca_cert_path_upload:
            $ref: '#/components/schemas/Meta'
          client_cert_path:
            $ref: '#/components/schemas/Meta'
          client_cert_path_upload:
            $ref: '#/components/schemas/Meta'
          client_key_path:
            $ref: '#/components/schemas/Meta'
          client_key_path_upload:
            $ref: '#/components/schemas/Meta'
          id:
            $ref: '#/components/schemas/Meta'
          server_cert_path:
            $ref: '#/components/schemas/Meta'
          server_cert_path_upload:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
