ConfigFirewallsMeta:
  discriminator:
    propertyName: type
  oneOf:
  - properties:
      meta:
        properties:
          cache_timeout:
            $ref: '#/components/schemas/Meta'
          cache_updates:
            $ref: '#/components/schemas/Meta'
          categories:
            $ref: '#/components/schemas/Meta'
          default_realm:
            $ref: '#/components/schemas/Meta'
          id:
            $ref: '#/components/schemas/Meta'
          networks:
            $ref: '#/components/schemas/Meta'
          password:
            $ref: '#/components/schemas/Meta'
          port:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
          uid:
            $ref: '#/components/schemas/Meta'
          use_connector:
            $ref: '#/components/schemas/Meta'
          username_format:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          cache_timeout:
            $ref: '#/components/schemas/Meta'
          cache_updates:
            $ref: '#/components/schemas/Meta'
          categories:
            $ref: '#/components/schemas/Meta'
          default_realm:
            $ref: '#/components/schemas/Meta'
          id:
            $ref: '#/components/schemas/Meta'
          networks:
            $ref: '#/components/schemas/Meta'
          password:
            $ref: '#/components/schemas/Meta'
          port:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
          uid:
            $ref: '#/components/schemas/Meta'
          use_connector:
            $ref: '#/components/schemas/Meta'
          username:
            $ref: '#/components/schemas/Meta'
          username_format:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          cache_timeout:
            $ref: '#/components/schemas/Meta'
          cache_updates:
            $ref: '#/components/schemas/Meta'
          categories:
            $ref: '#/components/schemas/Meta'
          default_realm:
            $ref: '#/components/schemas/Meta'
          id:
            $ref: '#/components/schemas/Meta'
          networks:
            $ref: '#/components/schemas/Meta'
          password:
            $ref: '#/components/schemas/Meta'
          port:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
          uid:
            $ref: '#/components/schemas/Meta'
          use_connector:
            $ref: '#/components/schemas/Meta'
          username:
            $ref: '#/components/schemas/Meta'
          username_format:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          cache_timeout:
            $ref: '#/components/schemas/Meta'
          cache_updates:
            $ref: '#/components/schemas/Meta'
          categories:
            $ref: '#/components/schemas/Meta'
          default_realm:
            $ref: '#/components/schemas/Meta'
          id:
            $ref: '#/components/schemas/Meta'
          networks:
            $ref: '#/components/schemas/Meta'
          password:
            $ref: '#/components/schemas/Meta'
          port:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
          uid:
            $ref: '#/components/schemas/Meta'
          use_connector:
            $ref: '#/components/schemas/Meta'
          username_format:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          cache_timeout:
            $ref: '#/components/schemas/Meta'
          cache_updates:
            $ref: '#/components/schemas/Meta'
          categories:
            $ref: '#/components/schemas/Meta'
          default_realm:
            $ref: '#/components/schemas/Meta'
          id:
            $ref: '#/components/schemas/Meta'
          nac_name:
            $ref: '#/components/schemas/Meta'
          networks:
            $ref: '#/components/schemas/Meta'
          password:
            $ref: '#/components/schemas/Meta'
          port:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
          uid:
            $ref: '#/components/schemas/Meta'
          use_connector:
            $ref: '#/components/schemas/Meta'
          username_format:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          cache_timeout:
            $ref: '#/components/schemas/Meta'
          cache_updates:
            $ref: '#/components/schemas/Meta'
          categories:
            $ref: '#/components/schemas/Meta'
          default_realm:
            $ref: '#/components/schemas/Meta'
          id:
            $ref: '#/components/schemas/Meta'
          networks:
            $ref: '#/components/schemas/Meta'
          password:
            $ref: '#/components/schemas/Meta'
          port:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
          uid:
            $ref: '#/components/schemas/Meta'
          use_connector:
            $ref: '#/components/schemas/Meta'
          username_format:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          cache_timeout:
            $ref: '#/components/schemas/Meta'
          cache_updates:
            $ref: '#/components/schemas/Meta'
          categories:
            $ref: '#/components/schemas/Meta'
          default_realm:
            $ref: '#/components/schemas/Meta'
          id:
            $ref: '#/components/schemas/Meta'
          networks:
            $ref: '#/components/schemas/Meta'
          password:
            $ref: '#/components/schemas/Meta'
          port:
            $ref: '#/components/schemas/Meta'
          transport:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
          uid:
            $ref: '#/components/schemas/Meta'
          use_connector:
            $ref: '#/components/schemas/Meta'
          username_format:
            $ref: '#/components/schemas/Meta'
          vsys:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          cache_timeout:
            $ref: '#/components/schemas/Meta'
          cache_updates:
            $ref: '#/components/schemas/Meta'
          categories:
            $ref: '#/components/schemas/Meta'
          default_realm:
            $ref: '#/components/schemas/Meta'
          id:
            $ref: '#/components/schemas/Meta'
          networks:
            $ref: '#/components/schemas/Meta'
          password:
            $ref: '#/components/schemas/Meta'
          port:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
          uid:
            $ref: '#/components/schemas/Meta'
          use_connector:
            $ref: '#/components/schemas/Meta'
          username_format:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          cache_timeout:
            $ref: '#/components/schemas/Meta'
          cache_updates:
            $ref: '#/components/schemas/Meta'
          categories:
            $ref: '#/components/schemas/Meta'
          default_realm:
            $ref: '#/components/schemas/Meta'
          deviceid:
            $ref: '#/components/schemas/Meta'
          id:
            $ref: '#/components/schemas/Meta'
          networks:
            $ref: '#/components/schemas/Meta'
          password:
            $ref: '#/components/schemas/Meta'
          port:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
          uid:
            $ref: '#/components/schemas/Meta'
          use_connector:
            $ref: '#/components/schemas/Meta'
          username_format:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          cache_timeout:
            $ref: '#/components/schemas/Meta'
          cache_updates:
            $ref: '#/components/schemas/Meta'
          categories:
            $ref: '#/components/schemas/Meta'
          default_realm:
            $ref: '#/components/schemas/Meta'
          id:
            $ref: '#/components/schemas/Meta'
          networks:
            $ref: '#/components/schemas/Meta'
          password:
            $ref: '#/components/schemas/Meta'
          port:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
          uid:
            $ref: '#/components/schemas/Meta'
          use_connector:
            $ref: '#/components/schemas/Meta'
          username_format:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          cache_timeout:
            $ref: '#/components/schemas/Meta'
          cache_updates:
            $ref: '#/components/schemas/Meta'
          categories:
            $ref: '#/components/schemas/Meta'
          default_realm:
            $ref: '#/components/schemas/Meta'
          id:
            $ref: '#/components/schemas/Meta'
          networks:
            $ref: '#/components/schemas/Meta'
          password:
            $ref: '#/components/schemas/Meta'
          port:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
          uid:
            $ref: '#/components/schemas/Meta'
          use_connector:
            $ref: '#/components/schemas/Meta'
          username_format:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          cache_timeout:
            $ref: '#/components/schemas/Meta'
          cache_updates:
            $ref: '#/components/schemas/Meta'
          categories:
            $ref: '#/components/schemas/Meta'
          default_realm:
            $ref: '#/components/schemas/Meta'
          id:
            $ref: '#/components/schemas/Meta'
          networks:
            $ref: '#/components/schemas/Meta'
          password:
            $ref: '#/components/schemas/Meta'
          port:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
          uid:
            $ref: '#/components/schemas/Meta'
          use_connector:
            $ref: '#/components/schemas/Meta'
          username_format:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
  - properties:
      meta:
        properties:
          cache_timeout:
            $ref: '#/components/schemas/Meta'
          cache_updates:
            $ref: '#/components/schemas/Meta'
          categories:
            $ref: '#/components/schemas/Meta'
          default_realm:
            $ref: '#/components/schemas/Meta'
          id:
            $ref: '#/components/schemas/Meta'
          networks:
            $ref: '#/components/schemas/Meta'
          password:
            $ref: '#/components/schemas/Meta'
          port:
            $ref: '#/components/schemas/Meta'
          type:
            $ref: '#/components/schemas/Meta'
          uid:
            $ref: '#/components/schemas/Meta'
          use_connector:
            $ref: '#/components/schemas/Meta'
          username:
            $ref: '#/components/schemas/Meta'
          username_format:
            $ref: '#/components/schemas/Meta'
        type: object
    type: object
