ConfigPortalModule:
  description: 'Choose one of the request bodies by discriminator (`type`). '
  discriminator:
    mapping:
      Authentication: '#/components/schemas/ConfigPortalModuleSubTypeAuthentication'
      Authentication::Billing: '#/components/schemas/ConfigPortalModuleSubTypeAuthenticationBilling'
      Authentication::Blackhole: '#/components/schemas/ConfigPortalModuleSubTypeAuthenticationBlackhole'
      Authentication::Choice: '#/components/schemas/ConfigPortalModuleSubTypeAuthenticationChoice'
      Authentication::Email: '#/components/schemas/ConfigPortalModuleSubTypeAuthenticationEmail'
      Authentication::Login: '#/components/schemas/ConfigPortalModuleSubTypeAuthenticationLogin'
      Authentication::Null: '#/components/schemas/ConfigPortalModuleSubTypeAuthenticationNull'
      Authentication::OAuth: '#/components/schemas/ConfigPortalModuleSubTypeAuthenticationOauth'
      Authentication::OAuth::Facebook: '#/components/schemas/ConfigPortalModuleSubTypeAuthenticationOauthFacebook'
      Authentication::OAuth::Github: '#/components/schemas/ConfigPortalModuleSubTypeAuthenticationOauthGithub'
      Authentication::OAuth::Google: '#/components/schemas/ConfigPortalModuleSubTypeAuthenticationOauthGoogle'
      Authentication::OAuth::LinkedIn: '#/components/schemas/ConfigPortalModuleSubTypeAuthenticationOauthLinkedin'
      Authentication::OAuth::OpenID: '#/components/schemas/ConfigPortalModuleSubTypeAuthenticationOauthOpenid'
      Authentication::OAuth::WindowsLive: '#/components/schemas/ConfigPortalModuleSubTypeAuthenticationOauthWindowslive'
      Authentication::Password: '#/components/schemas/ConfigPortalModuleSubTypeAuthenticationPassword'
      Authentication::SAML: '#/components/schemas/ConfigPortalModuleSubTypeAuthenticationSaml'
      Authentication::SMS: '#/components/schemas/ConfigPortalModuleSubTypeAuthenticationSms'
      Authentication::Sponsor: '#/components/schemas/ConfigPortalModuleSubTypeAuthenticationSponsor'
      Chained: '#/components/schemas/ConfigPortalModuleSubTypeChained'
      Choice: '#/components/schemas/ConfigPortalModuleSubTypeChoice'
      FixedRole: '#/components/schemas/ConfigPortalModuleSubTypeFixedrole'
      MFA: '#/components/schemas/ConfigPortalModuleSubTypeMfa'
      Message: '#/components/schemas/ConfigPortalModuleSubTypeMessage'
      Provisioning: '#/components/schemas/ConfigPortalModuleSubTypeProvisioning'
      Root: '#/components/schemas/ConfigPortalModuleSubTypeRoot'
      RootSSO: '#/components/schemas/ConfigPortalModuleSubTypeRootsso'
      SSL_Inspection: '#/components/schemas/ConfigPortalModuleSubTypeSslInspection'
      SelectRole: '#/components/schemas/ConfigPortalModuleSubTypeSelectrole'
      ShowLocalAccount: '#/components/schemas/ConfigPortalModuleSubTypeShowlocalaccount'
      Survey: '#/components/schemas/ConfigPortalModuleSubTypeSurvey'
      URL: '#/components/schemas/ConfigPortalModuleSubTypeUrl'
    propertyName: type
  oneOf:
  - $ref: '#/components/schemas/ConfigPortalModuleSubTypeAuthenticationOauthGithub'
  - $ref: '#/components/schemas/ConfigPortalModuleSubTypeChoice'
  - $ref: '#/components/schemas/ConfigPortalModuleSubTypeAuthenticationOauth'
  - $ref: '#/components/schemas/ConfigPortalModuleSubTypeAuthenticationOauthFacebook'
  - $ref: '#/components/schemas/ConfigPortalModuleSubTypeRootsso'
  - $ref: '#/components/schemas/ConfigPortalModuleSubTypeAuthenticationLogin'
  - $ref: '#/components/schemas/ConfigPortalModuleSubTypeAuthenticationOauthLinkedin'
  - $ref: '#/components/schemas/ConfigPortalModuleSubTypeAuthenticationChoice'
  - $ref: '#/components/schemas/ConfigPortalModuleSubTypeSelectrole'
  - $ref: '#/components/schemas/ConfigPortalModuleSubTypeChained'
  - $ref: '#/components/schemas/ConfigPortalModuleSubTypeMfa'
  - $ref: '#/components/schemas/ConfigPortalModuleSubTypeAuthenticationNull'
  - $ref: '#/components/schemas/ConfigPortalModuleSubTypeAuthentication'
  - $ref: '#/components/schemas/ConfigPortalModuleSubTypeAuthenticationOauthWindowslive'
  - $ref: '#/components/schemas/ConfigPortalModuleSubTypeProvisioning'
  - $ref: '#/components/schemas/ConfigPortalModuleSubTypeUrl'
  - $ref: '#/components/schemas/ConfigPortalModuleSubTypeShowlocalaccount'
  - $ref: '#/components/schemas/ConfigPortalModuleSubTypeAuthenticationOauthGoogle'
  - $ref: '#/components/schemas/ConfigPortalModuleSubTypeRoot'
  - $ref: '#/components/schemas/ConfigPortalModuleSubTypeAuthenticationBilling'
  - $ref: '#/components/schemas/ConfigPortalModuleSubTypeAuthenticationBlackhole'
  - $ref: '#/components/schemas/ConfigPortalModuleSubTypeSslInspection'
  - $ref: '#/components/schemas/ConfigPortalModuleSubTypeMessage'
  - $ref: '#/components/schemas/ConfigPortalModuleSubTypeAuthenticationSaml'
  - $ref: '#/components/schemas/ConfigPortalModuleSubTypeSurvey'
  - $ref: '#/components/schemas/ConfigPortalModuleSubTypeAuthenticationPassword'
  - $ref: '#/components/schemas/ConfigPortalModuleSubTypeAuthenticationSponsor'
  - $ref: '#/components/schemas/ConfigPortalModuleSubTypeAuthenticationOauthOpenid'
  - $ref: '#/components/schemas/ConfigPortalModuleSubTypeFixedrole'
  - $ref: '#/components/schemas/ConfigPortalModuleSubTypeAuthenticationSms'
  - $ref: '#/components/schemas/ConfigPortalModuleSubTypeAuthenticationEmail'
