openapi: "3.0.0"
  
info:
  title: PacketFence API
  description: An API to access the PacketFence resources. Lets make the PacketFence API great again!
  version: 0.0.1
    
servers:
  - url: https://127.0.0.1:9999/api/v1
      
security:
  - bearerAuth: []
   

      
