---
environment__group_variables:
  - name: 'PF_TEST_MGMT_INT'
    value: "{{ packetfence_install__mgmt_interface['id'] }}"
    
  - name: 'PF_TEST_MGMT_IP'
    value: "{{ packetfence_install__mgmt_interface['ip'] }}"
    
  - name: 'PF_TEST_MGMT_MASK'
    value: "{{ packetfence_install__mgmt_interface['mask'] }}"

