---
# hack to get id of mgmt interface based
# on IP assigned by vagrant
mgmt_interface_id: "{{ ansible_facts | dict2items | selectattr('value.ipv4', 'defined') | selectattr('value.ipv4.address', 'equalto', mgmt_ip) | first }}"

packetfence_install__mgmt_interface:
  id: "{{ mgmt_interface_id['key'] }}"
  ip: "{{ mgmt_ip }}"
  mask: "{{ mgmt_netmask }}"
  type: management,portal
